### ISSUE TITLE
sowatchmk2 1.15.1 http://www.youku.com/

### ISSUE THREAD

**Issue by 1608637229** [jc3213/Misc#10]
点击图标切换过滤模式无反应，需要重启插件才能看到效果，优酷的替换视频我怀疑是假的，因为无法切换1080P视频，以前是可以的，现在chrome也是可以的，优酷还出现了45秒黑屏，爱奇艺某些视频过滤很慢，

**Comment by 1608637229** [comment]
好吧，重新试了下发现可以看1080p,切换过滤模式需要重启插件才有效果，这个问题依然存在

**Comment by jc3213** [comment]
这个现象是因为火狐缓存机制导致得，再隐私模式下直接Ctrl+F5即可立刻体验到切换后得效果（至少45那会还是有效果得）
