### ISSUE TITLE
sowatchmk2 1.15.1 http://www.youku.com/

### ISSUE THREAD

**Issue by ailinhomu** [jc3213/Misc#11]
![20170205211832](https://cloud.githubusercontent.com/assets/12998371/22626462/d3ae7a5a-ebe8-11e6-9b3b-81fc4946e656.png)

如图，soWatch正常工作后，能过滤广告，但是flash播放器的控制条被挡住了

**Comment by ailinhomu** [comment]
暂时用CSS把挡flash的那条东西给隐藏了

**Comment by jc3213** [comment]
这个是破解播放器的问题，目前唯一的解决方案就是使用stylish或者userContent.css还是userChrome.css之类的东西去解决了

**Comment by ailinhomu** [comment]
临时解决方案：
用ABP之类的广告屏蔽扩展添加下面的元素隐藏规则，把分享条隐藏掉
```
v.youku.com###vpactionv5_wrap
```

**Comment by jc3213** [comment]
这个问题已经在 [1.15.2](https://github.com/jc3213/soWatch-mk2/releases/tag/1.15.2) 中解决了
