### ISSUE TITLE
经常更新，经常弹窗，这样不好

### ISSUE THREAD

**Issue by jdfq** [jc3213/Misc#12]
如题

**Comment by jc3213** [comment]
做Panel系通知我并做不好。虽然我很乐意去尝试。

**Comment by jc3213** [comment]
Panel做起来貌似并不难，目前soWatch mk2最新commit已经实现，不过只显示更新内容这部分不会做。这里慢慢来吧

**Comment by caliban511** [comment]
没觉得有经常过………………

**Comment by jc3213** [comment]
已更换提醒方式，虽然并不像Chrome原生的那么方便。需要等待网页加载完成才行。这部分需要额外的修改，以后再说了。
