### ISSUE TITLE
The default path of offline player is Windows only

### ISSUE THREAD

**Issue by gitterliu** [jc3213/Misc#18]
The default path of offline player is `soWatch\*.swf`.
It's OK if using Windows. But in Linux that just create filenames begin with `soWatch\`, not folder soWatch with swf files in it.

**Comment by jc3213** [comment]
The extension itself uses `OS.File.jsm` api or `nsIFile` instance, it access `Profiles\soWatch` directory by default.

I don't have Linux environment for debugging, May be I'll try a better approach to solve this problem.

**Comment by gitterliu** [comment]
@jc3213 1.16.1 has fix it.
