### ISSUE TITLE
火狐刚启动时失效

### ISSUE THREAD

**Issue by Arrow-Li** [jc3213/Misc#20]
设Google为主页，启动时无法连接
<img src="http://i4.buimg.com/4851/a95e6601f9d69f51.png">
在新建一个标签页之后，就能正常访问Google了

**Comment by jc3213** [comment]
什么意思不太明白？

**Comment by Arrow-Li** [comment]
Google设为主页，火狐打开的时候无法连接。
jc3213 <notifications@github.com>于2017年4月9日 周日13:09写道：

**Comment by Arrow-Li** [comment]
https://youtu.be/27LEDipmjR0

**Comment by jc3213** [comment]
@Arrow-Li 你的意思是，刚启动火狐时代理无法工作，需要等待一段时间才行？这个问题多半是因为扩展启动，加载列表，注册事件的延迟导致的。也许跟扩展本身代理的优先级较低有关。你试试用个短规则看看有没有同样的问题？或者生成PAC试试？

**Comment by Arrow-Li** [comment]
换了只有一条的短规则就正常了，生成PAC并没有作用。

**Comment by jc3213** [comment]
@Arrow-Li 生成的PAC不工作么？ 如果短规则正常，那么应该是扩展启动+读取列表+转换规则+匹配规则这个过程带来的延迟影响了代理效果。这个或许可以通过修改代理的优先级来解决。但我不准备改。

回头我自己再看一下PAC部分

**Comment by Arrow-Li** [comment]
我换成本地规则好像就正常了，本地完整的gfwlist.txt
jc3213 <notifications@github.com>于2017年4月9日 周日15:31写道：

**Comment by Arrow-Li** [comment]
之前用的远程规则
.盼头 <jeep3333@gmail.com>于2017年4月9日 周日15:32写道：

**Comment by Arrow-Li** [comment]
可能是初始化时每次都会更新一次gfwlist而导致的延时么？
.盼头 <jeep3333@gmail.com>于2017年4月9日 周日15:33写道：

**Comment by jc3213** [comment]
默认的行为是检查文件是否是4天前的才更新，因此应该不是因为这个导致的问题。再就是，通过SimpleScriptLoader+SimpleProxy.ss.js测试，重启后依然会进入代理（未导入xx证书会提示证书错误）。扩展等我再试试

**Comment by Arrow-Li** [comment]
但是换成本地的gfwlist就不会延迟，应该和规则长短没有问题。 另外我用的是SS

jc3213 <notifications@github.com>于2017年4月9日周日 下午3:39写道：

**Comment by jc3213** [comment]
我是用远程gfwlist(本地已下载好），不管是生成的pac，扩展，脚本，都能在启动后打开谷歌主页时直接出现证书错误。（并没有导入证书）。个人推测这个问题跟你其他扩展，脚本环境有关。

我这边测试环境为51.0.1 64位，Windows 10.0.15063.13

**Comment by Arrow-Li** [comment]
53.0b9, 15063.13

[image: 图片.png]

jc3213 <notifications@github.com>于2017年4月9日周日 下午3:44写道：

**Comment by Arrow-Li** [comment]
现在用一个本地规则加上一个远程GFWLIST，能解决这个问题

.盼头 <jeep3333@gmail.com>于2017年4月9日周日 下午3:48写道：

53.0b9, 15063.13

[image: 图片.png]

jc3213 <notifications@github.com>于2017年4月9日周日 下午3:44写道：

我是用远程gfwlist(本地已下载好），不管是生成的pac，扩展，脚本，都能在启动后打开谷歌主页时直接出现证书错误。（并没有导入证书）。个人推测这个问题跟你其他扩展，脚本环境有关。

我这边测试环境为51.0.1 64位，Windows 10.0.15063.13

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jc3213/Misc/issues/20#issuecomment-292770246>, or mute
the thread

**Comment by jc3213** [comment]
@Arrow-Li 抱歉，我完全无法复现你的故障。请你尝试使用纯净档案进行测试，并自行排查脚本或扩展冲突。我这边测试完全正常，因此我也无能为力。

你的图片上传失败，我无法查看。

**Comment by Arrow-Li** [comment]
email回复里插入不了图片，现在这样能用就可以，谢谢了
