### ISSUE TITLE
优酷换播放器不能播放了

### ISSUE THREAD

**Issue by jdfq** [jc3213/Misc#24]
如题

**Comment by jc3213** [comment]
请尝试刷新。请更新播放器。目前规则方面没有太大的问题，貌似是优酷本身的问题。参考卡饭讨论

**Comment by hacker873** [comment]
好像是不好用了，播放器是最新的，MK2也是最新的，还是无法播放

**Comment by jc3213** [comment]
好歹吧，我也是做了反馈功能的，你们反馈也带上链接吧？

然后可以的话请附带 Adblock Plus 可过滤项目 关键词.swf 的截图给我
