### ISSUE TITLE
iqiyi不能使用特殊播放器

### ISSUE THREAD

**Issue by a18ccms** [jc3213/Misc#3]
iqiyi不能使用特殊播放器，是过滤规则有问题吗？

**Comment by jc3213** [comment]
我不太明白特殊播放器的意义？请提交对应的链接。如果是直播页面的话是不支持的

**Comment by a18ccms** [comment]
就是iqiyi 不能替换特别版播放器。不能免AD。 例如这个：http://www.iqiyi.com/v_19rrlexats.html#vfrm=2-3-0-1

**Comment by jc3213** [comment]
你试试别另外个选择能否过滤广告？也许是爱奇艺更新规则了。你装个Adblock Plus。

然后打开`可过滤项目`的下边栏，然后输入关键词.swf，然后再打开这个页面，把内容给我看下。因为我没有火狐所以Debug比较麻烦

**Comment by jdfq** [comment]
装个火狐不难

**Comment by jdfq** [comment]
选择 拦截XML请求 ，爱奇艺暂时未见广告。

**Comment by jc3213** [comment]
@jdfq 因为火狐毛病太多，我伺候不起已经换Chrome了。

**Comment by a18ccms** [comment]
http://msg.71.am/cp2.gif?b=490930300&x=http%3A%2F%2Fwww.iqiyi.com%2Fcommon%2Fflashplayer%2F20160818%2F1530f98c2359.swf%7C%7Chttp%3A%2F%2Fwww.iqiyi.com%2Fcommon%2Fflashplayer%2F20160817%2Fam-3-38-0.swf&y=qc_100001_100451&pl=0&e=ad2f7ca88265f70142da1dd1161cd52f&p=v&lc=http%3A%2F%2Fwww.iqiyi.com%2Fv_19rrlexats.html%23vfrm%3D2-3-0-1&av=3.5.0&s=1471931344820&vv=5.3.2.19&t=s&u=d35d311f68047ce8acedc5c49d103dc4&fp=WIN%2022,0,0,209&v=490930300&c=31
http://msg.71.am/cp2.gif?em=http%3A%2F%2Fwww.iqiyi.com%2Fcommon%2Fflashplayer%2F20160815%2F5ad6994a81fc43d09327372977a85cba.swf&s=1471931375081&y=qc_100001_100451&rc=1&e=ad2f7ca88265f70142da1dd1161cd52f&ec=504&ai=6||71000028||81000019||54000042435||pause&g=0&d=4261&b=203924801&a=e4bdea60483b2414391a2cc2db3cbd21&c=31&av=AdManager%203.38.0&p=c&l=MjIxLjguNjQuMTYy&vv=5.3.2.19&t=e&u=d35d311f68047ce8acedc5c49d103dc4&rid=479741e74887a15b926b4ed62678a941
http://msg.71.am/cp2.gif?em=http%3A%2F%2Fwww.iqiyi.com%2Fcommon%2Fflashplayer%2F20160815%2F5ad6994a81fc43d09327372977a85cba.swf&s=1471931375098&y=qc_100001_100451&rc=-1&e=ad2f7ca88265f70142da1dd1161cd52f&ec=504&ai=6||71000028||81000019||54000042435||pause&g=0&d=4261&b=203924801&a=e4bdea60483b2414391a2cc2db3cbd21&c=31&av=AdManager%203.38.0&p=c&l=MjIxLjguNjQuMTYy&vv=5.3.2.19&t=e&u=d35d311f68047ce8acedc5c49d103dc4&rid=479741e74887a15b926b4ed62678a941
http://msg.video.qiyi.com/vodpb.gif?url=http://www.iqiyi.com/common/flashplayer/20160818/18242a1b82aa.swf&tag=done&curl=http://www.iqiyi.com/common/flashplayer/20160818/18242a1b82aa.swf&useTime=124&dur=3713
http://www.iqiyi.com/common/flashplayer/20160425/15455aa9a57.swf
http://www.iqiyi.com/common/flashplayer/20160817/am-3-38-0.swf
http://www.iqiyi.com/common/flashplayer/20160818/1530f98c2359.swf
http://www.iqiyi.com/common/flashplayer/20160818/18242a1b82aa.swf
http://www.iqiyi.com/player/cupid/common/clear.swf?r=a64skc
http://www.iqiyi.com/player/cupid/common/clear.swf?r=o8nmwj
http://www.iqiyi.com/player/cupid/common/icon.swf

**Comment by jc3213** [comment]
已更新规则，回头推送新版本 https://github.com/jc3213/soWatch-mk2/releases/tag/1.12.10
