### ISSUE TITLE
Again, to WebRequest.jsm

### ISSUE THREAD

**Issue by jc3213** [jc3213/Misc#4]
重新尝试用WebRequest改写中，不过看了下Redirect部分貌似无法像Chrome扩展那样（因为不能基于tabId跟windowId进行筛选）感觉几乎没戏。不过做下前置部分也不错，至少有意义吧

[sowatchmk2-2.0.1b1-src.zip](https://github.com/jc3213/Misc/files/438920/sowatchmk2-2.0.1b1-src.zip)

[sowatchmk2-2.0.1b1.xpi.zip](https://github.com/jc3213/Misc/files/438921/sowatchmk2-2.0.1b1.xpi.zip)

**Comment by msghost** [comment]
FF47.0，用release那边的xpi看优酷提示2004，用这个就好了。

**Comment by jc3213** [comment]
@msghost 因为这个没做任何功能，23333333。HttpRequest.js保存着但是事件监听并没有注册，因此相关功能都不会工作，WebRequest.js里面则直接提供的console.log。

**Comment by msghost** [comment]
表示不懂程序。。完全看不懂。。嗯。。貌似FF上除了你的作品以外就没有什么有效的防视频广告了。希望一切顺利吧。。

**Comment by jc3213** [comment]
火狐版WebRequest跟微软版一样，不支持tabId跟windowId，实现对应功能会变得非常麻烦。而且参考对可能存在得后续维护者的友好性问题，最后回滚了MatchPattern得修改，返回正则表达式，并在正则表达式得基础上增加了对类ABP字符串规则得支持。即使不会写正则表达式，用字符串写规则也是可以的。
