### ISSUE TITLE
不知道为什么，火狐无法过滤广告了。

### ISSUE THREAD

**Issue by zasl** [jc3213/Misc#6]
重新删除并且安装，然后火狐里面的网络内容缓存也清除了，就是不行。。。。

**Comment by jc3213** [comment]
一脸懵逼？

**Comment by zasl** [comment]
彻底懵逼了。。。。

**Comment by jc3213** [comment]
我也很懵逼，不知道你表达了什么？关键信息啥都没有，大兄弟

**Comment by jc3213** [comment]
如果48小时内依然无法提供详细信息以供Debug，本issue将关闭 @zasl
