### ISSUE TITLE
能不能增加对17173的支持呢？

### ISSUE THREAD

**Issue by l0rraine** [jc3213/Misc#7]
rt
不知道麻烦不麻烦，谢谢先

**Comment by jc3213** [comment]
17173不搞播放器的话固定黑屏15秒（至少之前是）因为播放器没人维护，一般广告可以ABP过滤，所以我这边没有添加。

PS：其实最开始是有的，不过维护播放器的人不再维护17173，而且17173大多数都是外链的视频因此也没必要单独针对维护了。
