### ISSUE TITLE
想要去广告得刷新一次网页

### ISSUE THREAD

**Issue by Tomsu2016** [jc3213/Misc#8]
来自firefox50.1.0：
在爱奇艺看视频的时候，使用特殊播放器，广告需要刷新一次网页才能去掉。
另外，其他播放器不太会用，只有特殊播放器能去广告？
如果可以不刷新直接去广告就好了。

**Comment by jc3213** [comment]
请清除缓存后再试。这种情况一般是先看过广告再切换规则后导致的

**Comment by Tomsu2016** [comment]
嗯，好了
